In [1]:
from numpy import genfromtxt
import numpy as np
import pandas as pd

**Load .csv file**

In [3]:
sub1 = genfromtxt('subm_res50_fconv_ver1.csv', delimiter=',')
sub2 = genfromtxt('subm_res50_fconv_ver2.csv', delimiter=',')
sub3 = genfromtxt('subm_res50_fconv_ver3.csv', delimiter=',')
sub4 = genfromtxt('subm_res50_fc_bneck.csv', delimiter=',')
sub5 = genfromtxt('subm_res50_fc_ver1.csv', delimiter=',')
sub6 = genfromtxt('subm_res50_incep.csv', delimiter=',')

[id, isDog]

In [4]:
sub1[:5]

array([[             nan,              nan],
       [  1.05920000e+04,   0.00000000e+00],
       [  7.21700000e+03,   3.00000000e-05],
       [  3.65300000e+03,   1.00000000e+00],
       [  4.38200000e+03,   1.48100000e-02]])

In [5]:
sub1 = sub1[1:]
sub2 = sub2[1:]
sub3 = sub3[1:]
sub4 = sub4[1:]
sub5 = sub5[1:]
sub6 = sub6[1:]

In [6]:
sub1[:5]

array([[  1.05920000e+04,   0.00000000e+00],
       [  7.21700000e+03,   3.00000000e-05],
       [  3.65300000e+03,   1.00000000e+00],
       [  4.38200000e+03,   1.48100000e-02],
       [  2.92400000e+03,   4.00570000e-01]])

**Average submissions**

In [16]:
arith_mean_subm = (sub1 + sub2 + sub3 + sub4 + sub5 + sub6)/6.
geo_mean_subm = np.power(sub1*sub2*sub3*sub4*sub5*sub6, 1/6.)

In [17]:
arith_mean_subm[:5]

array([[  1.05920000e+04,   1.60000000e-04],
       [  7.21700000e+03,   5.16666667e-05],
       [  3.65300000e+03,   1.00000000e+00],
       [  4.38200000e+03,   4.92000000e-03],
       [  2.92400000e+03,   6.66530000e-01]])

In [30]:
geo_mean_subm[0]

array([ 10592.,      0.])

**Do clipping to get lower log-loss on kaggle**

In [34]:
arith_mean_subm_isdog = arith_mean_subm[:,1]
arith_mean_subm_isdog = arith_mean_subm_isdog.clip(min=0.02/7, max=0.98)
arith_mean_subm_clip = np.stack([arith_mean_subm[:,0],arith_mean_subm_isdog], axis=1)

geo_mean_subm_isdog = geo_mean_subm[:,1]
geo_mean_subm_isdog = geo_mean_subm_isdog.clip(min=0.02/7, max=0.98)
geo_mean_subm_clip = np.stack([geo_mean_subm[:,0],geo_mean_subm_isdog], axis=1)

In [35]:
arith_mean_subm_clip[:5]

array([[  1.05920000e+04,   2.85714286e-03],
       [  7.21700000e+03,   2.85714286e-03],
       [  3.65300000e+03,   9.80000000e-01],
       [  4.38200000e+03,   4.92000000e-03],
       [  2.92400000e+03,   6.66530000e-01]])

In [36]:
geo_mean_subm_clip[:5]

array([[  1.05920000e+04,   2.85714286e-03],
       [  7.21700000e+03,   2.85714286e-03],
       [  3.65300000e+03,   9.80000000e-01],
       [  4.38200000e+03,   3.21343418e-03],
       [  2.92400000e+03,   5.96950014e-01]])

In [37]:
submission_file_name = 'arith_mean_subm_clip.csv'
np.savetxt(submission_file_name, arith_mean_subm_clip, fmt='%d,%.5f', header='id,label', comments='')
submission_file_name = 'geo_mean_subm_clip.csv'
np.savetxt(submission_file_name, geo_mean_subm_clip, fmt='%d,%.5f', header='id,label', comments='')